import { createContext, useState, useContext, ReactNode, useEffect } from "react";

// Automatisk versjonsgenerering basert på dagens dato
function getAutoVersion(): string {
  const now = new Date();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${month},${day}`;
}

export type Language = "no" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Export useTranslation as an alias for useLanguage for consistency with naming conventions
export const useTranslation = () => useLanguage();

// Oversettelser
const translations: Record<Language, Record<string, string>> = {
  no: {
    // Support page
    "support.customerSupport": "Kundeservice",
    "support.customerSupportDesc": "Vi er her for å hjelpe deg. Velg en av kontaktmetodene nedenfor.",
    "support.howCanWeHelp": "Hvordan kan vi hjelpe deg?",
    "support.tickets": "Kundeservice henvendelser",
    "support.myTickets": "Mine henvendelser",
    "support.newTicket": "Ny henvendelse",
    "support.ticketsList": "Henvendelsesliste",
    "support.yourSupportTickets": "Dine kundeservice henvendelser",
    "support.noTickets": "Ingen henvendelser funnet",
    "support.createYourFirstTicket": "Opprett din første henvendelse ved å klikke på 'Ny henvendelse'",
    "support.noTicketSelected": "Ingen henvendelse valgt",
    "support.selectTicketFromList": "Velg en henvendelse fra listen til venstre",
    "support.createNewTicket": "Opprett ny henvendelse",
    "support.createNewTicketDesc": "Fyll ut skjemaet nedenfor for å opprette en ny henvendelse til kundeservice",
    "support.ticketTitle": "Tittel på henvendelse",
    "support.ticketTitlePlaceholder": "Kort beskrivelse av henvendelsen",
    "support.noMessages": "Ingen meldinger i denne henvendelsen ennå",
    "support.typeYourMessage": "Skriv din melding her...",
    "support.category.technical": "Teknisk problem",
    "support.category.billing": "Fakturering",
    "support.category.support": "Kundestøtte",
    "support.category.info": "Informasjonsforespørsel",
    "support.category.complaint": "Klage",
    "support.message": "Melding",
    "support.messagePlaceholder": "Beskriv henvendelsen din her...",
    "support.submitTicket": "Send henvendelse",
    "support.creatingTicket": "Sender henvendelse...",
    "support.ticketCreated": "Henvendelse sendt",
    "support.ticketCreatedDesc": "Din henvendelse er mottatt og vil bli behandlet av kundeservice",
    "support.error": "En feil oppstod",
    "support.fillRequiredFields": "Vennligst fyll ut alle påkrevde felt",
    "support.category": "Kategori",
    "support.chooseContactMethod": "Velg en kontaktmetode for å komme i kontakt med vårt kundeserviceteam.",
    "support.liveChat": "Live chat",
    "support.call": "Ring oss",
    "support.email": "E-post",
    "support.startChatting": "Start en chat med oss",
    "support.chatInstructions": "Klikk på knappen under for å starte en live chat med en av våre kundeservicerepresentanter.",
    "support.openChat": "Start chat",
    "support.chatHours": "Tilgjengelig: {hours}",
    "support.callUs": "Ring oss",
    "support.callUsDesc": "Du kan nå oss på telefon under våre åpningstider.",
    "support.emailUs": "Send oss en e-post",
    "support.emailUsDesc": "Send oss en e-post og vi vil svare så snart som mulig.",
    "support.sendEmail": "Send e-post",
    "support.contactInfo": "Kontaktinformasjon",
    "support.phoneNumber": "Telefonnummer",
    "support.emailAddress": "E-postadresse",
    "support.businessHours": "Åpningstider",
    "support.commonTopics": "Vanlige temaer",
    "support.accountIssues": "Kontoproblemer",
    "support.accountIssuesDesc": "Problemer med innlogging, passord eller kontoinformasjon",
    "support.calendarIssues": "Kalenderproblemer",
    "support.calendarIssuesDesc": "Problemer med hendelser, synkronisering eller visning",
    "support.technicalIssues": "Tekniske problemer",
    "support.technicalIssuesDesc": "Generelle tekniske problemer med applikasjonen",
    "support.viewFAQ": "Se vanlige spørsmål (FAQ)",
    
    // Generelle
    "app.title": "BOOKING KALENDER | Smart Hjem AS",
    "translation.button": "Oversett",
    "translation.backToOriginal": "Vis original",
    "translation.translating": "Oversetter...",
    "translation.error": "Kunne ikke oversette tekst",
    "common.loading": "Laster...",
    "common.cancel": "Avbryt",
    "common.save": "Lagre",
    "common.back": "Tilbake",
    "common.processing": "Behandler...",
    "common.unknown": "Ukjent",
    "common.unknownDate": "Ukjent dato",
    "common.user": "Bruker",
    
    // Sakshåndtering
    "caseManagement.pageTitle": "Kundeservice | Smart Hjem AS",
    "caseManagement.title": "Kundeservice & Support",
    "caseManagement.newCase": "Ny henvendelse",
    "caseManagement.openCases": "Åpne saker",
    "caseManagement.closedCases": "Lukkede saker",
    "caseManagement.noOpenCases": "Ingen åpne saker",
    "caseManagement.noOpenCasesDescription": "Du har ingen åpne kundeservicesaker. Klikk på knappen nedenfor for å opprette en ny sak.",
    "caseManagement.createFirstCase": "Opprett første sak",
    "caseManagement.noClosedCases": "Ingen lukkede saker",
    "caseManagement.noClosedCasesDescription": "Du har ingen lukkede kundeservicesaker.",
    "caseManagement.noCaseSelected": "Ingen sak valgt",
    "caseManagement.selectCaseDescription": "Velg en sak fra listen til venstre for å se detaljer og meldinger.",
    "caseManagement.caseNotFound": "Saken ble ikke funnet",
    "caseManagement.caseNotFoundDescription": "Saken du leter etter finnes ikke eller har blitt slettet.",
    "caseManagement.viewCase": "Vis sak",
    "caseManagement.category": "Kategori",
    "caseManagement.categoryTechnical": "Teknisk",
    "caseManagement.categoryBilling": "Fakturering",
    "caseManagement.categoryAccount": "Konto",
    "caseManagement.categoryCalendar": "Kalender",
    "caseManagement.categoryOther": "Annet",
    "caseManagement.priority": "Prioritet",
    "caseManagement.priorityHigh": "Høy",
    "caseManagement.priorityMedium": "Medium",
    "caseManagement.priorityLow": "Lav",
    "caseManagement.status": "Status",
    "caseManagement.statusOpen": "Åpen",
    "caseManagement.statusInProgress": "Under behandling",
    "caseManagement.statusResolved": "Løst",
    "caseManagement.closed": "Lukket",
    "caseManagement.assignedToAdmin": "Tildelt",
    "caseManagement.assignedToDepartment": "Tildelt avdeling",
    "caseManagement.customerService": "Kundeservice",
    "caseManagement.message": "Melding",
    "caseManagement.messageRequired": "Melding er påkrevd",
    "caseManagement.messagePlaceholder": "Beskriv ditt spørsmål eller problem...",
    "caseManagement.typeMessage": "Skriv en melding...",
    "caseManagement.noMessages": "Ingen meldinger",
    "caseManagement.noMessagesDescription": "Det er ingen meldinger i denne saken ennå.",
    "caseManagement.newCaseTitle": "Opprett ny kundeservicesak",
    "caseManagement.newCaseDescription": "Fyll ut skjemaet nedenfor for å opprette en ny sak til kundeservice.",
    "caseManagement.caseTitle": "Tittel",
    "caseManagement.caseTitlePlaceholder": "Kort beskrivelse av saken",
    "caseManagement.selectCategory": "Velg kategori",
    "caseManagement.selectPriority": "Velg prioritet",
    "caseManagement.createCase": "Opprett sak",
    "caseManagement.caseCreatedTitle": "Sak opprettet",
    "caseManagement.caseCreatedDescription": "Din sak er opprettet og vil bli behandlet av kundeservice.",
    "caseManagement.errorTitle": "Feil",
    "caseManagement.closeCase": "Lukk sak",
    "caseManagement.reopenCase": "Gjenåpne sak",
    "caseManagement.assignToMe": "Tildel til meg",
    "caseManagement.closeCaseTitle": "Lukk sak",
    "caseManagement.closeCaseDescription": "Er du sikker på at du vil lukke denne saken?",
    "caseManagement.closeCaseConfirmation": "Når en sak lukkes, vil den flyttes til arkivet. Du kan gjenåpne saken senere hvis det skulle være nødvendig.",
    "caseManagement.confirmClose": "Ja, lukk sak",
    "caseManagement.caseClosed": "Sak lukket",
    "caseManagement.caseClosedDescription": "Saken er nå lukket.",
    "caseManagement.reopenCaseTitle": "Gjenåpne sak",
    "caseManagement.reopenCaseDescription": "Er du sikker på at du vil gjenåpne denne saken?",
    "caseManagement.reopenCaseConfirmation": "Hvis du gjenåpner saken, vil den flyttes tilbake til aktive saker og kundeservice vil bli varslet.",
    "caseManagement.confirmReopen": "Ja, gjenåpne sak",
    "caseManagement.caseReopened": "Sak gjenåpnet",
    "caseManagement.caseReopenedDescription": "Saken er nå gjenåpnet.",
    "caseManagement.caseAssigned": "Sak tildelt",
    "caseManagement.caseAssignedDescription": "Saken er nå tildelt til deg.",
    "caseManagement.assignCase": "Tildel sak",
    "caseManagement.assignCaseDescription": "Velg en administrator eller avdeling som skal tildeles denne saken.",
    "caseManagement.selectAdmin": "Velg administrator/avdeling",
    "caseManagement.selectAdminPlaceholder": "Velg en administrator eller avdeling",
    "caseManagement.departments": "Avdelinger",
    "caseManagement.individualAdmins": "Individuelle administratorer",
    "caseManagement.assign": "Tildel",
    "caseManagement.allUsers": "Alle brukere",
    "caseManagement.selectRecipient": "Velg mottaker",
    "caseManagement.messageToOwner": "Melding til saksoppretteren",
    "caseManagement.messageToAdmin": "Melding til administrator",
    "caseManagement.caseOwner": "Saksoppretteren",
    "caseManagement.assignedAdmin": "Tildelt administrator",
    "caseManagement.targetedMessage": "Denne meldingen vil kun være synlig for den valgte brukeren",
    "caseManagement.generalMessage": "Denne meldingen vil være synlig for alle",
    "caseManagement.adminMessage": "Denne meldingen vil være synlig for alle administratorer",
    "caseManagement.messageSendError": "Kunne ikke sende melding. Prøv igjen senere.",
    "caseManagement.toUser": "Til bruker",
    "caseManagement.caseCreatedBy": "Sak opprettet av",
    "caseManagement.sendingMessage": "Sender melding",
    "caseManagement.sendingMessageTo": "Melding sendes til",
    "caseManagement.sendingMessageToAll": "Melding sendes til alle involverte",
    
    "caseManagement.dateNotAvailable": "Dato ikke tilgjengelig",
    
    "validation.titleMinLength": "Tittel må være minst {count} tegn",
    
    // Price management translations
    "prices.yourPricesPerDay": "Dine priser pr dag",
    "prices.priceRanges": "Prisintervaller",
    "prices.readOnlyBadge": "Kun visning",
    "prices.year": "År",
    "prices.priceFrom": "Pris fra",
    "prices.priceTo": "Pris til",
    "prices.discount": "Rabatt %",
    "prices.status": "Status",
    "prices.actions": "Handlinger",
    "prices.active": "Aktiv",
    "prices.inactive": "Inaktiv",
    "prices.editTooltip": "Rediger prisintervall",
    "prices.deleteTooltip": "Slett prisintervall",
    "prices.selectUserMessage": "Velg en bruker for å se prisintervaller",
    "prices.noPricesFound": "Ingen prisintervaller funnet",
    "prices.createNewRange": "Opprett nytt prisintervall",
    "prices.editRange": "Rediger prisintervall",
    "prices.name": "Navn",
    "prices.namePlaceholder": "F.eks. 'Standard pakke'",
    "prices.priceFromLabel": "Pris fra (kr)",
    "prices.priceToLabel": "Pris til (kr)",
    "prices.discountLabel": "Rabatt (%)",
    "prices.activeLabel": "Aktiv",
    "prices.cancel": "Avbryt",
    "prices.create": "Opprett",
    "prices.creating": "Oppretter...",
    "prices.saveChanges": "Lagre endringer",
    "prices.saving": "Lagrer...",
    
    // Settings page translations
    "settings.userSettings": "Brukerinnstillinger",
    "settings.manageAccount": "Administrer din konto og personlige innstillinger",
    "settings.profile": "Profil",
    "settings.password": "Passord",
    "settings.calendarLink": "Kalender-lenke",
    "settings.name": "Navn",
    "settings.email": "E-post",
    "settings.username": "Brukernavn",
    "settings.usernameCannotChange": "Brukernavnet kan ikke endres",
    "settings.saveChanges": "Lagre endringer",
    "settings.deleteAccount": "Slett konto",
    "settings.deleteAccountConfirm": "Er du sikker på at du vil slette kontoen din?",
    "settings.deleteAccountWarning": "Dette vil slette all din informasjon og alle dine kalenderdata permanent. Denne handlingen kan ikke angres.",
    "settings.allDataWillBeDeleted": "Alle dine hendelser og dataene dine vil bli slettet permanent.",
    "settings.cancel": "Avbryt",
    "settings.deleteMyAccount": "Slett kontoen min",
    "settings.currentPassword": "Nåværende passord",
    "settings.newPassword": "Nytt passord",
    "settings.confirmPassword": "Bekreft passord",
    "settings.updatePassword": "Oppdater passord",
    "settings.personalCalendarUrl": "Din personlige kalender-URL",
    "settings.calendarUrlDescription": "Bruk denne URLen for å abonnere på din personlige kalender fra eksterne kalender-applikasjoner som Google Calendar, Apple Calendar eller Microsoft Outlook.",
    "settings.copyUrl": "Kopier URL",
    "settings.openInNewTab": "Åpne i ny fane",
    "settings.importInstructions": "Instruksjoner for import",
    
    // Calendar translations
    "calendar.title": "Kalender",
    "calendar.today": "I dag",
    "calendar.month": "Måned",
    "calendar.week": "Uke",
    "calendar.day": "Dag",
    "calendar.selectUser": "Velg bruker...",
    "calendar.myCalendar": "Min kalender",
    
    "validation.titleMaxLength": "Tittel kan ikke være lengre enn {count} tegn",
    "validation.categoryRequired": "Kategori er påkrevd",
    "validation.priorityRequired": "Prioritet er påkrevd",
    "validation.messageMinLength": "Melding må være minst {count} tegn",
    "validation.messageMaxLength": "Melding kan ikke være lengre enn {count} tegn",
    
    // Innloggingsside
    "login.welcome": "Velkommen",
    "login.subtitle": "Logg inn på kontoen din",
    "login.email": "E-post",
    "login.emailPlaceholder": "Skriv inn e-postadresse",
    "login.password": "Passord",
    "login.passwordPlaceholder": "Skriv inn passord",
    "login.button": "Logg inn",
    "login.button.loading": "Logger inn...",
    "login.newAccount": "Nye kontoer opprettes av en administrator.",
    "login.calendar": "Kalender",
    "login.tagline": "Din personlige reservasjonsassistent",
    "login.hero.title": "Organiser kalenderen din effektivt",
    "login.hero.description": "Administrer avtaler, hold oversikt over viktige datoer, og vær synkronisert med eksterne kalendere ved hjelp av vår iCal-integrasjon.",
    "login.feature1.title": "Personlig Kalender",
    "login.feature1.description": "Legg til og administrer alle avtaler på ett sted",
    "login.feature2.title": "Flere Visninger",
    "login.feature2.description": "Bytt mellom måned, uke og dag visninger",
    "login.feature3.title": "iCal Integrasjon",
    "login.feature3.description": "Synkroniser med eksterne kalendere via iCal-feeder",
    "login.customerService": "Kundeservice",
    "login.sendEmail": "Send e-post",
    "login.copyright": `Alle rettigheter reservert. Versjon ${getAutoVersion()}`,
    
    // Password Reset Page
    "reset.title": "Tilbakestill passord",
    "reset.description": "Skriv inn ditt nye passord for å tilbakestille kontoen din",
    "reset.newPassword": "Nytt passord",
    "reset.confirmPassword": "Bekreft nytt passord",
    "reset.button": "Tilbakestill passord",
    "reset.backToLogin": "Tilbake til innlogging",
    "reset.goToLogin": "Gå til innlogging",
    "reset.success": "Passord tilbakestilt",
    "reset.successDesc": "Ditt passord er nå endret. Du kan nå logge inn med ditt nye passord.",
    "reset.error.title": "Feil",
    "reset.error.noToken": "Ingen tilbakestillingstoken funnet i URL-en. Vennligst bruk lenken fra e-posten din.",
    "reset.error.minLength": "Passordet må være minst 6 tegn langt",
    "reset.error.mismatch": "Passordene matcher ikke",
    "reset.error.noTokenAvailable": "Ingen tilbakestillingstoken tilgjengelig",
    "reset.error.generic": "Det oppstod en feil ved tilbakestilling av passordet ditt",
    
    // Kontaktinformasjon
    "contact.company": "Smart Hjem AS",
    "contact.phone": "Tlf: 47 71 46 46",
    "contact.hours": "Kontortid: Man-Fre 09:00-16:00",
    
    // Navigation
    "nav.calendar": "Kalender",
    "nav.collaboration": "Samarbeid",
    "nav.settings": "Innstillinger",
    "nav.prices": "Dine priser",
    "nav.pricesAdmin": "Prisintervaller",
    "nav.adminTools": "Adminverktøy",
    "nav.users": "Administrasjon"
  },
  en: {
    // General
    "app.title": "BOOKING CALENDAR | Smart Hjem AS",
    "translation.button": "Translate",
    "translation.backToOriginal": "Show original",
    "translation.translating": "Translating...",
    "translation.error": "Could not translate text",
    "common.loading": "Loading...",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.back": "Back",
    "common.processing": "Processing...",
    "common.unknown": "Unknown",
    "common.unknownDate": "Unknown date",
    "common.user": "User",
    
    // Case Management
    "caseManagement.pageTitle": "Customer Service | Smart Hjem AS",
    "caseManagement.title": "Customer Service & Support",
    "caseManagement.newCase": "New inquiry",
    "caseManagement.openCases": "Open cases",
    "caseManagement.closedCases": "Closed cases",
    "caseManagement.noOpenCases": "No open cases",
    "caseManagement.noOpenCasesDescription": "You have no open customer service cases. Click the button below to create a new case.",
    "caseManagement.createFirstCase": "Create first case",
    "caseManagement.noClosedCases": "No closed cases",
    "caseManagement.noClosedCasesDescription": "You have no closed customer service cases.",
    "caseManagement.noCaseSelected": "No case selected",
    "caseManagement.selectCaseDescription": "Select a case from the list on the left to view details and messages.",
    "caseManagement.caseNotFound": "Case not found",
    "caseManagement.caseNotFoundDescription": "The case you are looking for does not exist or has been deleted.",
    "caseManagement.viewCase": "View case",
    "caseManagement.category": "Category",
    "caseManagement.categoryTechnical": "Technical",
    "caseManagement.categoryBilling": "Billing",
    "caseManagement.categoryAccount": "Account",
    "caseManagement.categoryCalendar": "Calendar",
    "caseManagement.categoryOther": "Other",
    "caseManagement.priority": "Priority",
    "caseManagement.priorityHigh": "High",
    "caseManagement.priorityMedium": "Medium",
    "caseManagement.priorityLow": "Low",
    "caseManagement.status": "Status",
    "caseManagement.statusOpen": "Open",
    "caseManagement.statusInProgress": "In progress",
    "caseManagement.statusResolved": "Resolved",
    "caseManagement.closed": "Closed",
    "caseManagement.assignedToAdmin": "Assigned to",
    "caseManagement.customerService": "Customer Service",
    "caseManagement.message": "Message",
    "caseManagement.messageRequired": "Message is required",
    "caseManagement.messagePlaceholder": "Describe your question or issue...",
    "caseManagement.typeMessage": "Type a message...",
    "caseManagement.noMessages": "No messages",
    "caseManagement.noMessagesDescription": "There are no messages in this case yet.",
    "caseManagement.allUsers": "All users (general message)",
    "caseManagement.caseOwner": "Case owner",
    "caseManagement.assignedAdmin": "Assigned administrator",
    "caseManagement.targetedMessage": "This message will only be sent to the selected user",
    "caseManagement.generalMessage": "This message will be visible to all users related to this case",
    "caseManagement.newCaseTitle": "Create new customer service case",
    "caseManagement.newCaseDescription": "Fill out the form below to create a new case for customer service.",
    "caseManagement.selectUser": "Select user for the case",
    "caseManagement.selectUserPlaceholder": "Select a user...",
    "caseManagement.createForMe": "Create case for myself",
    "caseManagement.creatingCaseForUser": "Creating case for selected user",
    "caseManagement.selectUserToCreate": "Select the user you want to create a case for",
    "caseManagement.caseTitle": "Title",
    "caseManagement.caseTitlePlaceholder": "Brief description of the case",
    "caseManagement.selectCategory": "Select category",
    "caseManagement.selectPriority": "Select priority",
    "caseManagement.createCase": "Create case",
    "caseManagement.caseCreatedTitle": "Case created",
    "caseManagement.caseCreatedDescription": "Your case has been created and will be processed by customer service.",
    "caseManagement.errorTitle": "Error",
    "caseManagement.closeCase": "Close case",
    "caseManagement.reopenCase": "Reopen case",
    "caseManagement.assignToMe": "Assign to me",
    "caseManagement.closeCaseTitle": "Close case",
    "caseManagement.closeCaseDescription": "Are you sure you want to close this case?",
    "caseManagement.closeCaseConfirmation": "When a case is closed, it will be moved to the archive. You can reopen the case later if necessary.",
    "caseManagement.confirmClose": "Yes, close case",
    "caseManagement.caseClosed": "Case closed",
    "caseManagement.caseClosedDescription": "The case is now closed.",
    "caseManagement.reopenCaseTitle": "Reopen case",
    "caseManagement.reopenCaseDescription": "Are you sure you want to reopen this case?",
    "caseManagement.reopenCaseConfirmation": "If you reopen the case, it will be moved back to active cases and customer service will be notified.",
    "caseManagement.confirmReopen": "Yes, reopen case",
    "caseManagement.caseReopened": "Case reopened",
    "caseManagement.caseReopenedDescription": "The case is now reopened.",
    "caseManagement.caseAssigned": "Case assigned",
    "caseManagement.caseAssignedDescription": "The case is now assigned to you.",
    "caseManagement.assignedToDepartment": "Assigned to department",
    "caseManagement.administrator": "Administrator",

    "caseManagement.categoryNotSpecified": "Not specified",
    "caseManagement.priorityNotSpecified": "Not specified",
    "caseManagement.dateNotAvailable": "Date not available",
    
    "validation.titleMinLength": "Title must be at least {count} characters",
    "validation.titleMaxLength": "Title cannot be longer than {count} characters",
    "validation.categoryRequired": "Category is required",
    "validation.priorityRequired": "Priority is required",
    "validation.messageMinLength": "Message must be at least {count} characters",
    
    // Price management translations
    "prices.yourPricesPerDay": "Your prices per day",
    "prices.priceRanges": "Price ranges",
    "prices.readOnlyBadge": "View only",
    "prices.year": "Year",
    "prices.priceFrom": "Price from",
    "prices.priceTo": "Price to",
    "prices.discount": "Discount %",
    "prices.status": "Status",
    "prices.actions": "Actions",
    "prices.active": "Active",
    "prices.inactive": "Inactive",
    "prices.editTooltip": "Edit price range",
    "prices.deleteTooltip": "Delete price range",
    "prices.selectUserMessage": "Select a user to view price ranges",
    "prices.noPricesFound": "No price ranges found",
    "prices.createNewRange": "Create new price range",
    "prices.editRange": "Edit price range",
    "prices.name": "Name",
    "prices.namePlaceholder": "E.g. 'Standard package'",
    "prices.priceFromLabel": "Price from (kr)",
    "prices.priceToLabel": "Price to (kr)",
    "prices.discountLabel": "Discount (%)",
    "prices.activeLabel": "Active",
    "prices.cancel": "Cancel",
    "prices.create": "Create",
    "prices.creating": "Creating...",
    "prices.saveChanges": "Save changes",
    "prices.saving": "Saving...",
    
    // Settings page translations
    "settings.userSettings": "User Settings",
    "settings.manageAccount": "Manage your account and personal settings",
    "settings.profile": "Profile",
    "settings.password": "Password",
    "settings.calendarLink": "Calendar Link",
    "settings.name": "Name",
    "settings.email": "Email",
    "settings.username": "Username",
    "settings.usernameCannotChange": "Username cannot be changed",
    "settings.saveChanges": "Save changes",
    "settings.deleteAccount": "Delete account",
    "settings.deleteAccountConfirm": "Are you sure you want to delete your account?",
    "settings.deleteAccountWarning": "This will permanently delete all your information and calendar data. This action cannot be undone.",
    "settings.allDataWillBeDeleted": "All your events and data will be permanently deleted.",
    "settings.cancel": "Cancel",
    "settings.deleteMyAccount": "Delete my account",
    "settings.currentPassword": "Current password",
    "settings.newPassword": "New password",
    "settings.confirmPassword": "Confirm password",
    "settings.updatePassword": "Update password",
    "settings.personalCalendarUrl": "Your personal calendar URL",
    "settings.calendarUrlDescription": "Use this URL to subscribe to your personal calendar from external calendar applications like Google Calendar, Apple Calendar or Microsoft Outlook.",
    "settings.copyUrl": "Copy URL",
    "settings.openInNewTab": "Open in new tab",
    "settings.importInstructions": "Import instructions",
    
    // Calendar translations
    "calendar.title": "Calendar",
    "calendar.today": "Today",
    "calendar.month": "Month",
    "calendar.week": "Week",
    "calendar.day": "Day",
    "calendar.selectUser": "Select user...",
    "calendar.myCalendar": "My calendar",
    
    "validation.messageMaxLength": "Message cannot be longer than {count} characters",
    
    // Login page
    "login.welcome": "Welcome",
    "login.subtitle": "Sign in to your account",
    "login.email": "Email",
    "login.emailPlaceholder": "Enter your email address",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.button": "Sign in",
    "login.button.loading": "Signing in...",
    "login.newAccount": "New accounts are created by an administrator.",
    "login.calendar": "Calendar",
    "login.tagline": "Your personal reservation assistant",
    "login.hero.title": "Organize your calendar efficiently",
    "login.hero.description": "Manage appointments, keep track of important dates, and stay synchronized with external calendars through our iCal integration.",
    "login.feature1.title": "Personal Calendar",
    "login.feature1.description": "Add and manage all appointments in one place",
    "login.feature2.title": "Multiple Views",
    "login.feature2.description": "Switch between month, week, and day views",
    "login.feature3.title": "iCal Integration",
    "login.feature3.description": "Synchronize with external calendars via iCal feeds",
    "login.customerService": "Customer Service",
    "login.sendEmail": "Send email",
    "login.copyright": `All rights reserved. Version ${getAutoVersion()}`,
    
    // Password Reset Page
    "reset.title": "Reset Password",
    "reset.description": "Enter your new password to reset your account",
    "reset.newPassword": "New password",
    "reset.confirmPassword": "Confirm new password",
    "reset.button": "Reset Password",
    "reset.backToLogin": "Back to login",
    "reset.goToLogin": "Go to login",
    "reset.success": "Password Reset",
    "reset.successDesc": "Your password has been changed. You can now log in with your new password.",
    "reset.error.title": "Error",
    "reset.error.noToken": "No reset token found in URL. Please use the link from your email.",
    "reset.error.minLength": "Password must be at least 6 characters long",
    "reset.error.mismatch": "Passwords do not match",
    "reset.error.noTokenAvailable": "No reset token available",
    "reset.error.generic": "An error occurred while resetting your password",
    
    // Contact information
    "contact.company": "Smart Hjem AS",
    "contact.phone": "Phone: 47 71 46 46",
    "contact.hours": "Office hours: Mon-Fri 09:00-16:00",
    
    // Navigation
    "nav.calendar": "Calendar",
    "nav.collaboration": "Collaboration", 
    "nav.settings": "Settings",
    "nav.prices": "Your prices",
    "nav.pricesAdmin": "Price ranges",
    "nav.adminTools": "Admin Tools",
    "nav.users": "Users"
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Sjekk localStorage for lagret språk, bruk norsk som standard
    const savedLanguage = localStorage.getItem("language") as Language;
    return savedLanguage === "en" ? "en" : "no";
  });

  useEffect(() => {
    // Lagre språkvalg i localStorage
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};